version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3

jobs:
  golang-lint:
    docker:
      - image: golang:1.18-alpine
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache git make bash curl
            # Go env
            go env
            # Install go libaries
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
            # Install golangci-lint
            # go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.50.1
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1
      - save_cache:
          paths: ["/go/pkg/mod"]
          key: go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: run lint
          command: |
            make lint 
  
  build-docker-image:
    machine: true
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: dunglh9-repo
          tag: 'latest,${CIRCLE_WORKFLOW_ID:0:7}'
  
  deploy-k8s:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Install kubectl
          command: |
            curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.22.15/2022-10-31/bin/darwin/amd64/kubectl
            chmod +x ./kubectl
            mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$HOME/bin:$PATH
            kubectl version --short --client
      - run:
          name: Update kube configuration
          command: |
            aws eks update-kubeconfig --region us-east-1 --name MyEKSCluster
      - run:
          name: Deploy pods
          command: |
            kubectl apply -f k8s/deployment.yml
            # kubectl apply -f k8s/service.yml
            # kubectl set image deployments/server-app server-app=016780080563.dkr.ecr.us-east-1.amazonaws.com/dunglh9-repo:${CIRCLE_WORKFLOW_ID:0:7}

workflows:
  default:
    jobs:
      # - golang-lint
      # - build-docker-image:
      #     requires: [golang-lint]
      # - build-docker-image
      # - deploy-k8s:
      #     requires: [build-docker-image]
      - deploy-k8s