version: 2.1

jobs:
  golang-lint:
    docker:
      - image: golang:1.18-alpine
    steps:
      - checkout
      # - restore_cache:
      #     keys: [go-libs]
      - run:
          name: Install dependencies
          command: |
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
            # Install golangci-lint
            go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.50.1
      # - save_cache:
      #     paths: [go-libs]
      #     key: go-libs
      - run:
          name: run lint
          command: |
            make lint 

workflows:
  default:
    jobs:
      - golang-lint