version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.1.3
  go: circleci/go@1.7.1
  

jobs:
  golang-lint:
    docker:
      - image: golang:1.18-alpine
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache git make bash curl
            # Go env
            go env
            # Install go libaries
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
            # Install golangci-lint
            # go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.50.1
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1
      - save_cache:
          paths: ["/go/pkg/mod"]
          key: go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: run lint
          command: |
            make lint 

  run-unit-test:
    executor:
      name: go/default
      tag: '1.18'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - go/test:
          covermode: atomic
          failfast: true
          race: true
  
  build-docker-image:
    machine: true
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: dunglh9-repo
          tag: 'latest,${CIRCLE_WORKFLOW_ID:0:7}'
  
  deploy-k8s:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Update kube configuration
          command: |
            aws eks update-kubeconfig --region us-east-1 --name MyEKSCluster
      - run:
          name: Deploy pods
          command: |
            curl -o kubectl https://s3.us-west-2.amazonaws.com/amazon-eks/1.22.15/2022-10-31/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            mkdir -p $HOME/bin && cp ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
            kubectl version --short --client
            kubectl apply -f k8s/deployment.yml
            kubectl apply -f k8s/service.yml
            kubectl set image deployments/server-app server-app=016780080563.dkr.ecr.us-east-1.amazonaws.com/dunglh9-repo:${CIRCLE_WORKFLOW_ID:0:7}

workflows:
  default:
    jobs:
      # - golang-lint
      - run-unit-test
      # - build-docker-image:
      #     requires: [golang-lint]
      # - build-docker-image
      # - deploy-k8s:
      #     requires: [build-docker-image]
      # - deploy-k8s