version: 2.1

jobs:
  golang-lint:
    docker:
      - image: golang:1.18-alpine
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache git make bash curl
            # Go env
            go env
            # Install go libaries
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
            # Install golangci-lint
            # go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.50.1
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1
      - save_cache:
          paths: ["/go/pkg/mod"]
          key: go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: run lint
          command: |
            make lint 

workflows:
  default:
    jobs:
      - golang-lint