version: 2.1

orbs:
  docker: circleci/docker@1.4.0

jobs:
  golang-lint:
    docker:
      - image: golang:1.18-alpine
    steps:
      - checkout
      - restore_cache:
          keys:
            - go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache git make bash curl
            # Go env
            go env
            # Install go libaries
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
            # Install golangci-lint
            # go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.50.1
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1
      - save_cache:
          paths: ["/go/pkg/mod"]
          key: go-mod-v1-{{ checksum "go.sum" }}
      - run:
          name: run lint
          command: |
            make lint 
  
  build-docker-image:
    machine: true
    steps:
      - checkout
      - run:
          name: Build image
          command: |
            docker --version
            docker build -t dunglh9/my-app .
            docker tag dunglh9/my-app dunglh9/my-app
      - run:
          name: Push image to Docker Hub
          command: |
            # docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
            docker push dunglh9/my-app
            echo "Pushed successfully"

workflows:
  default:
    jobs:
      # - golang-lint
      - build-docker-image